### ISSUE TITLE
Cannot find Kache?

### ISSUE THREAD

**Issue by koolfreak** [MayakaApps/Kache#114]
![image](https://user-images.githubusercontent.com/1182352/235439990-2c23008a-177b-442a-9a7c-e2dc0a3699ec.png)

After loading the dependency cannot find Kache?

**Comment by koolfreak** [comment]
..and also i try to follow the docs on how to setup the cache and i am not quite sure is i am doing it correctly:

![image](https://user-images.githubusercontent.com/1182352/235451148-15bb3098-0296-413c-8843-28e4c29dcc56.png)

also got this error:

java.lang.NoSuchMethodError: 'okio.FileSystem com.mayakapps.kache.FileSystemJvmKt.getDefaultFileSystem()'
	at com.mayakapps.kache.OkioFileKache$Configuration.<init>(OkioFileKache.kt:205)
	at com.mayakapps.kache.OkioFileKache$Companion.invoke(OkioFileKache.kt:237)

...sorry quite new to this caching thing

Thanks

**Comment by MSDarwish2000** [comment]
It seems that you added the dependency for `FileKache` only which is `com.mayakapps.kache:file-kache`. This artifact doesn't expose `Kache` until now. I'm still not sure if it should expose it or not. Let's keep this issue open as a reminder for this.

Currently, if you want to use `Kache`, also add `com.mayakapps.kache:kache` depedency.

For the second issue, you're reporting. It was caused by KMP bug (most probably related to [KT-47144](https://youtrack.jetbrains.com/issue/KT-47144)). I've added a work around for it in 2.0.0-rc02. If you're using 2.0.0-rc01, please update. If you're using a SNAPSHOT version, try refreshing dependencies or using rc02 instead.

Let me know if the issues persist.

**Comment by koolfreak** [comment]
ok thanks...at first im trying the in-memory cache but since it cannot recognize the Kacke class, tried the FileKache..

Also this is more of a request, do I using this api correctly? I just followed your docs. Can you give more examples on how to use this api? Im developing a rest-api using Ktor and i want to cache the image url of the users of the app. The app is a social-media like apps so profile avatars will be accessed frequently and i dont want to read them in the db always

Thanks

**Comment by enrico-de** [comment]
> For the second issue, you're reporting. It was caused by KMP bug (most probably related to [KT-47144](https://youtrack.jetbrains.com/issue/KT-47144)). I've added a work around for it in 2.0.0-rc02. If you're using 2.0.0-rc01, please update. If you're using a SNAPSHOT version, try refreshing dependencies or using rc02 instead.
> 
> Let me know if the issues persist.

For me 2.0.0-rc02 doesn't work. I am still getting seeing 
```
java.lang.NoSuchMethodError: 'okio.FileSystem com.mayakapps.kache.FileSystemJvmKt.getDefaultFileSystem()'
```
during runtime. Is there any other workaround available?

**Comment by MSDarwish2000** [comment]
@koolfreak @enrico-de I apologize for my late response for personal reasons. If you are still interested, please try the latest beta version v2.1.0-beta01 which, I think, fixes the issues that faced you.

**Comment by MSDarwish2000** [comment]
I'm closing this issue for now as it is supposed to be fixed. Feel free to re-open it if the issue remains.
