### ISSUE TITLE
Java 17 and Modules

### ISSUE THREAD

**Issue by Icosider** [MayakaApps/Kache#233]
**Describe the bug**
If you use the Java 9+ modular system, in my case 17, then a packaging error occurs

**To Reproduce**
1. Add file-kache-jvm.jar and kache-jvm.jar in ur classpath
2. Run ur app
3. See the error

**Expected behavior**
Running app without errors

**System (please complete the following information):**
 - Device: Desktop
 - OS: Windows 11

**Stacktrace**
```txt
Exception in thread "main" java.lang.module.ResolutionException: Modules file.kache.jvm and kache.jvm export package com.mayakapps.kache to module org.jsoup
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
```

**Comment by MSDarwish2000** [comment]
Thank you for reporting the issue. I would investigate and try to fix it soon.
